### ISSUE TITLE
Warning:Supported source version 'RELEASE_7' from annotation processor 

### ISSUE THREAD

**Issue by stephane-couget** [vimeo/stag-java#100]
Hello, I use Android Studio 2.4 preview7 with During the compilation of Stag I obtain an alert:
Warning:Supported source version 'RELEASE_7' from annotation processor 'com.vimeo.stag.processor.StagProcessor' less than -source '1.8'

Actually, I work with jdk1.8 

It can raise a problem of compilation ?
If yes, you propose a workaround solution?
It will be useful to plan a RELEASE_8 ?

**Comment by anthonycr** [comment]
Thanks for the report, should be an easy fix to accept java 8 code on stag's end. Look out for a release with a fix soon.

**Comment by anthonycr** [comment]
Fixed by https://github.com/vimeo/stag-java/releases/tag/v2.1.4
