### ISSUE TITLE
HashMap support

### ISSUE THREAD

**Issue by fleficher** [vimeo/stag-java#11]
#### Issue Summary

Support HashMap
#### Reproduction Steps

Use  @GsonAdapterKey on a HashMap field.
#### Expected Behavior

When generating parser for hashmap fields, use TypeToken from GSON instead of HashMap<String, String>.class.
#### Actual Behavior

stag generate a compilation error in ParseUtils :

```
if (object.urls!= null) { 
            writer.name("urls");
            Stag.writeToAdapter(gson, java.util.HashMap<java.lang.String,java.lang.String>.class, writer, object.urls);
}
ParseUtils.java:73: error: illegal start of expression Stag.writeToAdapter(gson, java.util.HashMap<java.lang.String,java.lang.String>.class, writer, object.urls);

....
try {
        object.urls= Stag.readFromAdapter(gson, java.util.HashMap<java.lang.String,java.lang.String>.class, reader);
} catch(Exception e) {
            throw new IOException("Error parsing Operation.urls JSON!");
}
ParseUtils.java:198: error: illegal start of expression object.urls= Stag.readFromAdapter(gson, java.util.HashMap<java.lang.String,java.lang.String>.class, reader);
```

**Comment by anirudhramanan** [comment]
Any update on this ?

**Comment by anthonycr** [comment]
I started working on it in this branch https://github.com/vimeo/stag-java/tree/hash-map-support, it's not fully functional yet. I need to get around to finishing it up

**Comment by anirudhramanan** [comment]
This issue should be addressed by the PR raised.

**Comment by anthonycr** [comment]
Fixed in this pr https://github.com/vimeo/stag-java/pull/20
