### ISSUE TITLE
How to upload video to Vimeo from Android app using this Library?

### ISSUE THREAD

**Issue by coneits** [vimeo/stag-java#13]
Hello.

I would like to upload video to vimeo from my android app.
Can I upload video from my android app using your github repository?
Or is there any other published github source code that can upload video?

Thanks,
Look forward to hearing from you.

Best Regards.

**Comment by kevinzetterstrom** [comment]
Hi @coneits 

This library is not Vimeo specific - it is a utility for helping with Gson (de)serialization.
Please see my answer to your same question [here](https://github.com/vimeo/vimeo-deeplink-android/issues/17).
