### ISSUE TITLE
Add compiler configuration for writing null values to JSON

### ISSUE THREAD

**Issue by anthonycr** [vimeo/stag-java#135]
#### Issue Summary
Currently, if the fields of an object are null, stag adapters skip writing those fields to JSON. This is valid behavior, but if you have default values which your fields are assigned to, then writing to JSON and then reading back out the object will result in unequal object.

#### Reproduction Steps
given the following object:
```java
class Test {
    @Nullable public String field;
    @Nullable public String field2 = "default";

    public Test(String field, String field2) { ... }
}
```
with values
```java
Test test = new Test("test", null);
```
the following JSON will be created
```json
{
"field":"test",
}
```
and when read from JSON, will result in the `Test` object having the following properties
```json
{
"field":"test",
"field2":"default"
}
```
which results in inequality. This is expected behavior and is not a bug, but we should provide a way to force the writing of null to the JSON so that the entire object state is preserved and default values are not used. This will still allow empty JSON to result in default assignment, but it will fix a problem where nullable fields with default values can cause inequality problems.

We should provide a compiler option that allows stag to force the writing of null fields to JSON.

related to this bug: https://github.com/vimeo/stag-java/issues/132

**Comment by yasirmhd** [comment]
Gson provides a [method](https://google.github.io/gson/apidocs/com/google/gson/GsonBuilder.html#serializeNulls--) where one can chose to serialize nulls.

We can probably leave Gson object to decide where nulls should be serialized or not. In the typeAdapter code that we generate we can put a null check and do a `writer.nullValue` in the event of the object value being null.



cc : @anthonycr

**Comment by anthonycr** [comment]
Fixed.
