### ISSUE TITLE
Fields referencing wildcarded generics cause compilation failure

### ISSUE THREAD

**Issue by mcumings** [vimeo/stag-java#155]
#### Issue Summary

Defining models with wild-carded generics such as the following result in invalid Java sources being generated for the TypeAdapter.

This scenario is useful when consuming models of varying types into a single collection.  For example, the code may leverage a provided type adapter factory to dynamically determine how to unmarshal the a JSON object payload, dynamically resolving the correct TypeAdapter to use for the object type being unmarshaled.

#### Reproduction Steps

Define a model which uses wildcarded generics such as the following:

```
@UseStag
public class DynamicallyTypedWildcardReadModel {
    public List<DynamicallyTypedModel<?>> models;
}
```

The generated code for the failing constructor looks like this:

```
  public DynamicallyTypedWildcardReadModel$TypeAdapter(Gson gson) {
    this.mGson = gson;
    com.google.gson.reflect.TypeToken<com.vimeo.sample_java_model.DynamicallyTypedModel<?>> typeToken0 = (com.google.gson.reflect.TypeToken<com.vimeo.sample_java_model.DynamicallyTypedModel<?>>)com.google.gson.reflect.TypeToken.getParameterized(com.vimeo.sample_java_model.DynamicallyTypedModel.class, ?.class);
    this.mTypeAdapter0 = gson.getAdapter(typeToken0);
    this.mTypeAdapter1 = new com.vimeo.stag.KnownTypeAdapters.ListTypeAdapter<com.vimeo.sample_java_model.DynamicallyTypedModel<?>,java.util.List<com.vimeo.sample_java_model.DynamicallyTypedModel<?>>>(mTypeAdapter0, new com.vimeo.stag.KnownTypeAdapters.ListInstantiator<com.vimeo.sample_java_model.DynamicallyTypedModel<?>>());
  }
```

Which results in compilation failure:

```
/Users/mcumings/src/github/stag-java/integration-test-java/build/generated/source/apt/main/com/vimeo/sample_java_model/DynamicallyTypedWildcardReadModel$TypeAdapter.java:28: error: illegal start of expression
    com.google.gson.reflect.TypeToken<com.vimeo.sample_java_model.DynamicallyTypedModel<?>> typeToken0 = (com.google.gson.reflect.TypeToken<com.vimeo.sample_java_model.DynamicallyTypedModel<?>>)com.google.gson.reflect.TypeToken.getParameterized(com.vimeo.sample_java_model.DynamicallyTypedModel.class, ?.class);
```

#### Expected Behavior

Stag generated code compiles and the behavior at runtime is identical to the behavior of Gson's ReflectiveTypeAdapter.

#### Actual Behavior

Compilation failure.

#### Workaround

Simply remove the `@UseStag` annotation for the model which contains the generics references to revert back to the built-in ReflectiveTypeAdapter (which works).

**Comment by mcumings** [comment]
This is a tough one from a code perspective.

A simple option would be to simply flag these as unsupported models, forcing these models to fall back to non-Stag ReflectiveTypeAdapter use.  That would be suboptimal as ALL fields for the enclosing model would then be handled by the default Gson behavior, but may be reasonable.

A better option which I have yet to find an acceptable way to code is to effectively mimic the ReflectiveTypeAdapter.  This has implications that fan-out.  For example, if the wildcard type is wrapped within a collection then we can't support KnownTypeAdapters (since it requires a TypeToken which we cannot provide without violating documented behavior).

**Comment by mcumings** [comment]
I just pushed #157 as an option for moving forward on this in the near term.  It simply flags such uses as a compile-time error which would force users to avoid Stag for these specific models, falling back on the Gson ReflectiveTypeAdapter to bridge the gap.

If we can find an actual solution then great.  If not, hopefully this will be useful.

**Comment by mcumings** [comment]
Okay, I'm out of time to work on this at the moment.  I raised #158 to capture a rough idea of what might be a sane approach but it needs some additional work.

@anthonycr - I've got to abandon this for a while to get back to the work I'm supposed to be working on.  I'm hoping these PRs can bootstrap you and/or someone else to allow this to be fixed in case I can't get back to it in a reasonable amount of time...

**Comment by anthonycr** [comment]
I'll review the associated PRs over the next few days 👍

**Comment by yasirmhd** [comment]
@anirudhramanan , let us think of a solution for this so that the entire class does not have to go through reflection. We can ensure that just this field will use reflection.

**Comment by mcumings** [comment]
Thanks for taking a look, all.

I should also note that all of the PRs are independent of each other.

**Comment by yasirmhd** [comment]
https://github.com/vimeo/stag-java/pull/161 should solve this. kindly review.

cc: @mcumings , @anthonycr

**Comment by mcumings** [comment]
Ah, I see what you did there.  I like that we know it's using the same mechanism as Gson.  Nice (and thanks)!  :+1:

**Comment by anthonycr** [comment]
Fixed by https://github.com/vimeo/stag-java/pull/161

**Comment by anthonycr** [comment]
I'll work on getting a 2.5.1 release out with the fix.

**Comment by mcumings** [comment]
Thanks @anthonycr
