### ISSUE TITLE
Support for Alternate names in while using SerializedName

### ISSUE THREAD

**Issue by anirudhramanan** [vimeo/stag-java#36]
Since @SerializedName has the option of specifying the alternate JSON names, along with the default JSON name, the generated type adapter should also take into account the alternate names while writing and reading objects.

**Comment by anthonycr** [comment]
https://github.com/vimeo/stag-java/releases/tag/v2.0.0 is released, so this can be closed, correct?

**Comment by anirudhramanan** [comment]
Yes. closing it
