### ISSUE TITLE
Not able to sync 2.0.0 version

### ISSUE THREAD

**Issue by anirudhramanan** [vimeo/stag-java#42]
Gradle is unable to resolve the 2.0.0 version of stag-compiler library.

**Comment by yasirmhd** [comment]
@anthonycr  : Can you please help with this?

**Comment by anthonycr** [comment]
Whoops, I just realized I pushed the gradle dependency but forgot to publish it. Publishing now

**Comment by anthonycr** [comment]
You should be all set, please close when you confirm

**Comment by anirudhramanan** [comment]
Working now, thanks!
