### ISSUE TITLE
Duplicate Classes generated

### ISSUE THREAD

**Issue by yasirmhd** [vimeo/stag-java#54]
#### Issue Summary
Duplicate classes are being generated when both the base class and derived class use @UseStag annotation and the base class exists in another module.

#### Reproduction Steps
Define a class in sample_model library

````java 
package com.vimeo.sample_model;

import com.vimeo.stag.UseStag;

@UseStag
public class BaseExternalModel {
    public String type;

    public int baseValue;

}
````

In sample app module add ExternalModelDerivedExample class
````java 
package com.vimeo.sample.model;

import com.vimeo.sample_model.BaseExternalModel;
import com.vimeo.stag.UseStag;

@UseStag
public class ExternalModelDerivedExample extends BaseExternalModel {

    public Boolean derivedBoolean;
}

````
#### Expected Behavior
It should create only one TypeAdapter for BaseExternalModel which should exist in the sample_module module only.

#### Actual Behavior
It generates two classes by BaseExternalModel$TypeAdapter in both the modules. Please check the screen shot below

What currently happens as a result of the reproduction steps?
![image](https://cloud.githubusercontent.com/assets/13655724/22642098/4f311e76-ec7f-11e6-92bb-4ddfb7d2c6e9.png)

**Comment by anthonycr** [comment]
Fixed by https://github.com/vimeo/stag-java/pull/55, tests to verify added here https://github.com/vimeo/stag-java/pull/57. Closing as fixed
