### ISSUE TITLE
java.util.concurrent.ExecutionException: com.android.dex.DexException

### ISSUE THREAD

**Issue by darwinfrancis** [vimeo/stag-java#83]
I successfully added the library with my android studio project and works fine but when i try to export the signed apk both debug and release build throws the following error.

> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Lorg/intellij/lang/annotations/Identifier;

#### Reproduction Steps
Add compile'com.vimeo.stag:stag-library:2.1.0' and apt 'com.vimeo.stag:stag-library-compiler:2.1.0' dependencies to your android project and sync, then try to export the signed apk

**Comment by anthonycr** [comment]
According to your stacktrace, it looks like the `com.intellij:annotations:12.0@jar` annotation dependency that stag relies on is somehow interfering with another dependency in your application. Try using the following dependency exclusion and see if that works for you:
```
compile ('com.vimeo.stag:stag-library:2.1.0') {
    exclude group: 'com.intellij', module: 'annotations'
}
apt ('com.vimeo.stag:stag-library-compiler:2.1.0') {
    exclude group: 'com.intellij', module: 'annotations'
}
```

**Comment by darwinfrancis** [comment]
Yes you are right, now it works fine... Thank your for your quick response.

**Comment by Armaxis** [comment]
I had a similar issue with Stag 2.6.0 and Android Studio 3.3.0 + Gradle 4.12

For me the following worked:

```
api ("com.vimeo.stag:stag-library:$stagVersion") {
    exclude group: 'org.jetbrains', module: 'annotations-java5'
}
annotationProcessor ("com.vimeo.stag:stag-library-compiler:$stagVersion") {
    exclude group: 'org.jetbrains', module: 'annotations-java5'
}
```
