### ISSUE TITLE
issue with TypeAdpater generation having Object fieldType

### ISSUE THREAD

**Issue by garganshul** [vimeo/stag-java#87]
#### Issue Summary
In case of object fieldType, typeadapter uses stagFactory but does not have stagFactory as a member variable.

#### Reproduction Steps
Create a class with having Object as one member variable, generated TypeAdapter will have compile time issue of mStagFactory not found.

#### Expected Behavior
mStagFactory is being used in adapter so it should be there as a member variable of class.

#### Actual Behavior
mStagFactory is being used but is not there as member variable.

**Comment by anthonycr** [comment]
Fixed by https://github.com/vimeo/stag-java/pull/88 and released in version 2.1.2. Closing.
