### ISSUE TITLE
Code breaking for subclass which has nested parametrized member variables

### ISSUE THREAD

**Issue by yasirmhd** [vimeo/stag-java#92]
#### Issue Summary
public class DummyGenericClass<T> {
    HashMap<String, List<T>> testArrayMap;
    ArrayList<Map<String, T>> testListMap;
}

public class DummyInheritedClass extends DummyGenericClass<String> {

}

Generation of TypeAdapter for DummyInheritedClass fails.

#### Reproduction Steps
Added unit tests. Use the above as an example

#### Expected Behavior
ArrayList<Map<String, T>> should resolve to ArrayList<Map<String, String>>

#### Actual Behavior
ArrayList<Map<String, T>> should resolve to ArrayList<String>

**Comment by anthonycr** [comment]
Closing as https://github.com/vimeo/stag-java/pull/93 has been merged
