### ISSUE TITLE
Stag-java does not support Kotlin

### ISSUE THREAD

**Issue by leisim** [vimeo/stag-java#99]
#### Issue Summary
Kotlin makes all fields private and that raises the stag exception: Unable to access field "x" in class Y, field must not be private.

#### Expected Behavior
It would be nice if there was a workaround for Kotlin ;)

**Comment by anthonycr** [comment]
I believe this could be supported if stag supported setters and getters instead of direct field access

**Comment by anthonycr** [comment]
You can track work on this in this branch: https://github.com/vimeo/stag-java/commits/kotlin-support

Support will include:
- Kotlin models will be able to use stag
- Java models will be able to make their members private if they provide getters/setters

**Comment by anthonycr** [comment]
PR is now open for this feature https://github.com/vimeo/stag-java/issues/104

**Comment by anthonycr** [comment]
Fixed by the latest release https://github.com/vimeo/stag-java/releases/tag/v2.2.0
